/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author 97250
 */
public class NewJPanel extends javax.swing.JPanel {
    boolean active = true;
    /**
     * Creates new form NewJPanel
     */
    public NewJPanel(String t, String description, String date) {
        initComponents();
        simpleTaskPanelTitleF.setText(t);
        simpleTaskPanelDescriptionF.setText(description);
        simpleTaskPanelDateF.setText(date);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simpleTaskPanel = new javax.swing.JPanel();
        activeCheckBox = new javax.swing.JCheckBox();
        simpleTaskPanelDescription = new javax.swing.JLabel();
        simpleTaskPanelTitle = new javax.swing.JLabel();
        simpleTaskPanelDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        simpleTaskPanelTitleF = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        simpleTaskPanelDateF = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        simpleTaskPanelDescriptionF = new javax.swing.JTextPane();

        activeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeCheckBoxActionPerformed(evt);
            }
        });

        simpleTaskPanelDescription.setText("description");

        simpleTaskPanelTitle.setText("title");

        simpleTaskPanelDate.setText("date created");

        jScrollPane1.setViewportView(simpleTaskPanelTitleF);

        jScrollPane3.setViewportView(simpleTaskPanelDateF);

        jScrollPane4.setViewportView(simpleTaskPanelDescriptionF);

        javax.swing.GroupLayout simpleTaskPanelLayout = new javax.swing.GroupLayout(simpleTaskPanel);
        simpleTaskPanel.setLayout(simpleTaskPanelLayout);
        simpleTaskPanelLayout.setHorizontalGroup(
            simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                .addGroup(simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(activeCheckBox))
                    .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(simpleTaskPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(simpleTaskPanelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(simpleTaskPanelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        simpleTaskPanelLayout.setVerticalGroup(
            simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activeCheckBox)
                .addGroup(simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(simpleTaskPanelDescription))
                            .addComponent(simpleTaskPanelTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpleTaskPanelDate)
                        .addGap(19, 19, 19))
                    .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(simpleTaskPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(simpleTaskPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void activeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeCheckBoxActionPerformed
        this.active = false;
    }//GEN-LAST:event_activeCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activeCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel simpleTaskPanel;
    private javax.swing.JLabel simpleTaskPanelDate;
    private javax.swing.JTextPane simpleTaskPanelDateF;
    private javax.swing.JLabel simpleTaskPanelDescription;
    private javax.swing.JTextPane simpleTaskPanelDescriptionF;
    private javax.swing.JLabel simpleTaskPanelTitle;
    private javax.swing.JTextPane simpleTaskPanelTitleF;
    // End of variables declaration//GEN-END:variables
}
