package com.mycompany.mavenproject1;

import Task.SimpleTask;
import Task.TaskArr;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 97250
 */
public class NewJFrame extends javax.swing.JFrame {
    TaskArr openTasks = new TaskArr() ;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTaskDialog = new javax.swing.JDialog();
        addTaskDialogPanel = new javax.swing.JPanel();
        addDatedTask = new javax.swing.JButton();
        addComplexTask = new javax.swing.JButton();
        addSimpelTask = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SimpleTask = new javax.swing.JDialog();
        addTaskDialogPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addSimpelTaskSubmit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taskDescription = new javax.swing.JTextArea();
        taskName = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        simpleTaskPanel = new javax.swing.JPanel();
        activeCheckBox = new javax.swing.JCheckBox();
        simpleTaskPanelDescription = new javax.swing.JLabel();
        simpleTaskPanelTitle = new javax.swing.JLabel();
        simpleTaskPanelDateC = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        simpleTaskPanelTitleF = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        simpleTaskPanelDateF = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        simpleTaskPanelDescriptionF = new javax.swing.JTextPane();
        MainPanel = new javax.swing.JScrollPane();
        TaskContainer = new javax.swing.JPanel();
        SimpleTaskSContainer = new javax.swing.JScrollPane();
        SimpleTaskContainer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        DatedTaskSContainer = new javax.swing.JScrollPane();
        DatedTaskContainer = new javax.swing.JPanel();
        ComplexTaskSContainer = new javax.swing.JScrollPane();
        ComplexTaskContainer = new javax.swing.JPanel();
        AddTaskBotton = new javax.swing.JButton();
        jMenu = new javax.swing.JMenuBar();
        CompletedMenu = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        ArrangeOption = new javax.swing.JMenu();
        Created = new javax.swing.JMenuItem();
        toComplete = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        addTaskDialog.setBounds(new java.awt.Rectangle(200, 80, 350, 150));

        addDatedTask.setText("dated task");
        addDatedTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDatedTaskActionPerformed(evt);
            }
        });

        addComplexTask.setText("complex task");

        addSimpelTask.setText("simple task");
        addSimpelTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSimpelTaskActionPerformed(evt);
            }
        });

        jLabel1.setText("chose task to add");

        javax.swing.GroupLayout addTaskDialogPanelLayout = new javax.swing.GroupLayout(addTaskDialogPanel);
        addTaskDialogPanel.setLayout(addTaskDialogPanelLayout);
        addTaskDialogPanelLayout.setHorizontalGroup(
            addTaskDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTaskDialogPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(addSimpelTask)
                .addGap(18, 18, 18)
                .addGroup(addTaskDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(addTaskDialogPanelLayout.createSequentialGroup()
                        .addComponent(addComplexTask)
                        .addGap(18, 18, 18)
                        .addComponent(addDatedTask)))
                .addContainerGap())
        );
        addTaskDialogPanelLayout.setVerticalGroup(
            addTaskDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTaskDialogPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(addTaskDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDatedTask)
                    .addComponent(addComplexTask)
                    .addComponent(addSimpelTask))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout addTaskDialogLayout = new javax.swing.GroupLayout(addTaskDialog.getContentPane());
        addTaskDialog.getContentPane().setLayout(addTaskDialogLayout);
        addTaskDialogLayout.setHorizontalGroup(
            addTaskDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addTaskDialogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        addTaskDialogLayout.setVerticalGroup(
            addTaskDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addTaskDialogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SimpleTask.setBounds(getBounds());

        jLabel2.setText("add simple task");

        jLabel3.setText("task name");

        jLabel5.setText("task description");

        addSimpelTaskSubmit.setText("submit task");
        addSimpelTaskSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSimpelTaskSubmitActionPerformed(evt);
            }
        });

        taskDescription.setColumns(20);
        taskDescription.setRows(5);
        jScrollPane2.setViewportView(taskDescription);

        taskName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addTaskDialogPanel1Layout = new javax.swing.GroupLayout(addTaskDialogPanel1);
        addTaskDialogPanel1.setLayout(addTaskDialogPanel1Layout);
        addTaskDialogPanel1Layout.setHorizontalGroup(
            addTaskDialogPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTaskDialogPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addSimpelTaskSubmit)
                .addGap(109, 109, 109))
            .addGroup(addTaskDialogPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(addTaskDialogPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(addTaskDialogPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(addTaskDialogPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(taskName)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        addTaskDialogPanel1Layout.setVerticalGroup(
            addTaskDialogPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskDialogPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(addTaskDialogPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(taskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(addTaskDialogPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addTaskDialogPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addSimpelTaskSubmit)
                        .addGap(18, 18, 18))
                    .addGroup(addTaskDialogPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(79, Short.MAX_VALUE))))
        );

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SimpleTaskLayout = new javax.swing.GroupLayout(SimpleTask.getContentPane());
        SimpleTask.getContentPane().setLayout(SimpleTaskLayout);
        SimpleTaskLayout.setHorizontalGroup(
            SimpleTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimpleTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addTaskDialogPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(SimpleTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SimpleTaskLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        SimpleTaskLayout.setVerticalGroup(
            SimpleTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimpleTaskLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(addTaskDialogPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(SimpleTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SimpleTaskLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        activeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeCheckBoxActionPerformed(evt);
            }
        });

        simpleTaskPanelDescription.setText("description");

        simpleTaskPanelTitle.setText("title");

        simpleTaskPanelDateC.setText("date created");

        jScrollPane1.setViewportView(simpleTaskPanelTitleF);

        jScrollPane3.setViewportView(simpleTaskPanelDateF);

        jScrollPane4.setViewportView(simpleTaskPanelDescriptionF);

        javax.swing.GroupLayout simpleTaskPanelLayout = new javax.swing.GroupLayout(simpleTaskPanel);
        simpleTaskPanel.setLayout(simpleTaskPanelLayout);
        simpleTaskPanelLayout.setHorizontalGroup(
            simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                .addGroup(simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(activeCheckBox))
                    .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(simpleTaskPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(simpleTaskPanelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(simpleTaskPanelDateC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        simpleTaskPanelLayout.setVerticalGroup(
            simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activeCheckBox)
                .addGroup(simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(simpleTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(simpleTaskPanelDescription))
                            .addComponent(simpleTaskPanelTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpleTaskPanelDateC)
                        .addGap(19, 19, 19))
                    .addGroup(simpleTaskPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        simpleTaskPanel.getAccessibleContext().setAccessibleName("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        SimpleTaskContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SimpleTaskContainer.setPreferredSize(new java.awt.Dimension(0, 90));

        jLabel4.setText("jLabel4");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout SimpleTaskContainerLayout = new javax.swing.GroupLayout(SimpleTaskContainer);
        SimpleTaskContainer.setLayout(SimpleTaskContainerLayout);
        SimpleTaskContainerLayout.setHorizontalGroup(
            SimpleTaskContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimpleTaskContainerLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        SimpleTaskContainerLayout.setVerticalGroup(
            SimpleTaskContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimpleTaskContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(SimpleTaskContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton1))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        SimpleTaskSContainer.setViewportView(SimpleTaskContainer);

        DatedTaskContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DatedTaskContainer.setPreferredSize(new java.awt.Dimension(0, 90));

        javax.swing.GroupLayout DatedTaskContainerLayout = new javax.swing.GroupLayout(DatedTaskContainer);
        DatedTaskContainer.setLayout(DatedTaskContainerLayout);
        DatedTaskContainerLayout.setHorizontalGroup(
            DatedTaskContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        DatedTaskContainerLayout.setVerticalGroup(
            DatedTaskContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        DatedTaskSContainer.setViewportView(DatedTaskContainer);

        ComplexTaskContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ComplexTaskContainer.setPreferredSize(new java.awt.Dimension(0, 90));

        javax.swing.GroupLayout ComplexTaskContainerLayout = new javax.swing.GroupLayout(ComplexTaskContainer);
        ComplexTaskContainer.setLayout(ComplexTaskContainerLayout);
        ComplexTaskContainerLayout.setHorizontalGroup(
            ComplexTaskContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        ComplexTaskContainerLayout.setVerticalGroup(
            ComplexTaskContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        ComplexTaskSContainer.setViewportView(ComplexTaskContainer);

        AddTaskBotton.setText("add task");
        AddTaskBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TaskContainerLayout = new javax.swing.GroupLayout(TaskContainer);
        TaskContainer.setLayout(TaskContainerLayout);
        TaskContainerLayout.setHorizontalGroup(
            TaskContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TaskContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComplexTaskSContainer)
                    .addComponent(SimpleTaskSContainer)
                    .addComponent(DatedTaskSContainer))
                .addContainerGap())
            .addGroup(TaskContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AddTaskBotton)
                .addContainerGap(508, Short.MAX_VALUE))
        );
        TaskContainerLayout.setVerticalGroup(
            TaskContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComplexTaskSContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SimpleTaskSContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DatedTaskSContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddTaskBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        MainPanel.setViewportView(TaskContainer);

        CompletedMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CompletedMenu.setText("Show competed");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("true");
        CompletedMenu.add(jCheckBoxMenuItem1);

        jMenu.add(CompletedMenu);

        ArrangeOption.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ArrangeOption.setText("arrange by");

        Created.setText("date created");
        ArrangeOption.add(Created);

        toComplete.setText("target date");
        ArrangeOption.add(toComplete);

        jMenuItem1.setText("jMenuItem1");
        ArrangeOption.add(jMenuItem1);

        jMenu.add(ArrangeOption);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddTaskBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskBottonActionPerformed
        addTaskDialog.setVisible(true);
    }//GEN-LAST:event_AddTaskBottonActionPerformed

    private void addDatedTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDatedTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDatedTaskActionPerformed

    private void addSimpelTaskSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSimpelTaskSubmitActionPerformed
        SimpleTask.setVisible(false);
        String title = taskName.getText();
        String desciption = taskDescription.getText();
        SimpleTask t = new SimpleTask(title,desciption);
        openTasks.addTask(t);
        NewJPanel p = new NewJPanel(title,desciption,t.convertDateToString(t.getCreateDate()));
        
        SimpleTaskContainer.add(p);
        p.setVisible(true);
        SimpleTaskContainer.revalidate();
        SimpleTaskContainer.repaint();
        SimpleTaskSContainer.revalidate();
        SimpleTaskSContainer.repaint();
        TaskContainer.revalidate();
        TaskContainer.repaint();
        MainPanel.revalidate();
        MainPanel.repaint();
        this.revalidate();
        this.repaint();
        
        
        

        
        
        
    }//GEN-LAST:event_addSimpelTaskSubmitActionPerformed

    private void taskNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskNameActionPerformed

    private void addSimpelTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSimpelTaskActionPerformed
        SimpleTask.setVisible(true);
        addTaskDialog.setVisible(false);
    }//GEN-LAST:event_addSimpelTaskActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void activeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activeCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTaskBotton;
    private javax.swing.JMenu ArrangeOption;
    private javax.swing.JMenu CompletedMenu;
    private javax.swing.JPanel ComplexTaskContainer;
    private javax.swing.JScrollPane ComplexTaskSContainer;
    private javax.swing.JMenuItem Created;
    private javax.swing.JPanel DatedTaskContainer;
    private javax.swing.JScrollPane DatedTaskSContainer;
    private javax.swing.JScrollPane MainPanel;
    private javax.swing.JDialog SimpleTask;
    private javax.swing.JPanel SimpleTaskContainer;
    private javax.swing.JScrollPane SimpleTaskSContainer;
    private javax.swing.JPanel TaskContainer;
    private javax.swing.JCheckBox activeCheckBox;
    private javax.swing.JButton addComplexTask;
    private javax.swing.JButton addDatedTask;
    private javax.swing.JButton addSimpelTask;
    private javax.swing.JButton addSimpelTaskSubmit;
    private javax.swing.JDialog addTaskDialog;
    private javax.swing.JPanel addTaskDialogPanel;
    private javax.swing.JPanel addTaskDialogPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel simpleTaskPanel;
    private javax.swing.JLabel simpleTaskPanelDateC;
    private javax.swing.JTextPane simpleTaskPanelDateF;
    private javax.swing.JLabel simpleTaskPanelDescription;
    private javax.swing.JTextPane simpleTaskPanelDescriptionF;
    private javax.swing.JLabel simpleTaskPanelTitle;
    private javax.swing.JTextPane simpleTaskPanelTitleF;
    private javax.swing.JTextArea taskDescription;
    private javax.swing.JTextField taskName;
    private javax.swing.JMenuItem toComplete;
    // End of variables declaration//GEN-END:variables
}
